import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { afterAll, describe, expect, it } from "vitest";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const script = join(repoRoot, "tools", "test-ratio.mjs");

interface Counts {
  readonly files: number;
  readonly lines: number;
}

interface DirectoryReport {
  readonly directory: string;
  readonly source: Counts;
  readonly test: Counts;
  readonly ratio: number | null;
}

interface PackageReport {
  readonly name: string;
  readonly scan: readonly string[];
  readonly directories: readonly DirectoryReport[];
  readonly source: Counts;
  readonly test: Counts;
  readonly excluded: number;
  readonly ratio: number | null;
  readonly ok: boolean;
}

interface RatioReport {
  readonly minimum: number;
  readonly packages: readonly PackageReport[];
  readonly ok: boolean;
}

interface Sink {
  write(text: string): boolean;
}

interface RatioIO {
  readonly root: string;
  readonly stdout: Sink;
  readonly stderr: Sink;
}

interface TestRatioTools {
  readonly MINIMUM_RATIO: number;
  measure(root: string): RatioReport;
  main(argv: readonly string[], io: RatioIO): number;
}

const tools = (await import(pathToFileURL(script).href)) as TestRatioTools;

const temporary: string[] = [];

afterAll(() => {
  for (const dir of temporary) rmSync(dir, { recursive: true, force: true });
});

function capture(): { readonly sink: Sink; text(): string } {
  const chunks: string[] = [];
  return {
    sink: {
      write(text: string) {
        chunks.push(text);
        return true;
      },
    },
    text: () => chunks.join(""),
  };
}

function run(argv: readonly string[], root: string): { status: number; out: string; err: string } {
  const out = capture();
  const err = capture();
  const status = tools.main(argv, { root, stdout: out.sink, stderr: err.sink });
  return { status, out: out.text(), err: err.text() };
}

function write(root: string, path: string, lines: readonly string[]): void {
  const file = join(root, path);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, `${lines.join("\n")}\n`);
}

function numbered(prefix: string, count: number): string[] {
  return Array.from({ length: count }, (_, index) => `export const ${prefix}${index} = ${index};`);
}

function writeTree(): string {
  const root = mkdtempSync(join(tmpdir(), "rex-test-ratio-"));
  temporary.push(root);
  write(root, "packages/rex/src/core/alpha.ts", [
    "export const alpha = 1;",
    "",
    "export const beta = alpha + 1;",
    "export const gamma = beta + 1;",
  ]);
  write(root, "packages/rex/src/core/alpha.test.ts", [
    'import { expect, it } from "vitest";',
    'import { alpha } from "./alpha.ts";',
    "",
    'it("alpha", () => {',
    "  expect(alpha).toBe(1);",
    "});",
  ]);
  write(root, "packages/rex/src/core/beta.ts", numbered("b", 10));
  write(root, "packages/rex/src/core/store.conformance.ts", numbered("c", 2));
  write(root, "packages/rex/src/core/catalog.generated.ts", numbered("g", 3));
  write(root, "packages/rex/src/core/banner.ts", ["// @generated by rex", ...numbered("n", 2)]);
  write(root, "packages/rex/src/core/notes.ts", [
    "",
    "// GENERATED by rex manifest. DO NOT EDIT: run rex manifest to regenerate.",
    ...numbered("m", 2),
  ]);
  write(root, "packages/rex/src/core/fixtures/app/page.ts", numbered("f", 4));
  write(root, "packages/rex/src/testing/index.ts", numbered("t", 2));
  write(root, "packages/rex/src/testing/fixtures/notes/page.ts", numbered("p", 3));
  write(root, "packages/rex/src/vite/rex-app.d.ts", ['declare module "rex:app";']);
  write(root, "packages/rex/src/core/README.md", ["# core"]);
  write(root, "examples/demo/server.ts", numbered("s", 2));
  write(root, "examples/demo/app/pages/home/view.tsx", numbered("v", 3));
  write(root, "examples/demo/app/pages/home/test/home.test.tsx", numbered("h", 2));
  write(root, "examples/demo/app/pages/home/test/wallet.ts", numbered("w", 1));
  write(root, "examples/demo/app/components/Card.tsx", numbered("k", 2));
  write(root, "examples/demo/app/components/ui/button.tsx", numbered("u", 9));
  write(root, "examples/demo/app/.cache/stale.ts", numbered("x", 5));
  write(root, "examples/demo/e2e/walk.ts", numbered("e", 4));
  write(root, "examples/demo/rex.config.ts", numbered("r", 3));
  return root;
}

const initialReport: RatioReport = {
  minimum: 1,
  packages: [
    {
      name: "packages/rex",
      scan: ["src"],
      directories: [
        {
          directory: "src/core",
          source: { files: 2, lines: 13 },
          test: { files: 2, lines: 7 },
          ratio: 7 / 13,
        },
        {
          directory: "src/testing",
          source: { files: 0, lines: 0 },
          test: { files: 1, lines: 2 },
          ratio: null,
        },
      ],
      source: { files: 2, lines: 13 },
      test: { files: 3, lines: 9 },
      excluded: 6,
      ratio: 9 / 13,
      ok: false,
    },
    {
      name: "examples/demo",
      scan: ["app", "server.ts", "e2e"],
      directories: [
        { directory: ".", source: { files: 1, lines: 2 }, test: { files: 0, lines: 0 }, ratio: 0 },
        {
          directory: "app/components",
          source: { files: 1, lines: 2 },
          test: { files: 0, lines: 0 },
          ratio: 0,
        },
        {
          directory: "app/pages/home",
          source: { files: 1, lines: 3 },
          test: { files: 2, lines: 3 },
          ratio: 1,
        },
        {
          directory: "e2e",
          source: { files: 0, lines: 0 },
          test: { files: 1, lines: 4 },
          ratio: null,
        },
      ],
      source: { files: 3, lines: 7 },
      test: { files: 3, lines: 7 },
      excluded: 1,
      ratio: 1,
      ok: true,
    },
  ],
  ok: false,
};

describe("tools/test-ratio.mjs", () => {
  it("counts non-blank source and test lines per directory, skipping fixtures, declarations, generated files and vendored ui components", () => {
    const root = writeTree();
    expect(tools.MINIMUM_RATIO).toBe(1);
    expect(tools.measure(root)).toEqual(initialReport);
  });

  it("prints a table per package and exits 0 without --check", () => {
    const root = writeTree();
    const result = run([], root);
    expect(result).toMatchObject({ status: 0, err: "" });
    expect(result.out).toContain("packages/rex (src)\n");
    expect(result.out).toContain("examples/demo (app, server.ts, e2e)\n");
    expect(result.out).toContain(
      "  directory    source files  source lines  test files  test lines  ratio\n",
    );
    expect(result.out).toMatch(/^ {2}src\/core {4}.*2 {12}13 {11}2 {11}7 {3}0\.54$/m);
    expect(result.out).toMatch(/^ {2}src\/testing .*0 {13}0 {11}1 {11}2 {6}-$/m);
    expect(result.out).toMatch(/^ {2}total .*2 {12}13 {11}3 {11}9 {3}0\.69$/m);
    expect(result.out).toMatch(/^ {2}\. .*1 {13}2 {11}0 {11}0 {3}0\.00$/m);
    expect(result.out).toMatch(/^ {2}app\/pages\/home .*1 {13}3 {11}2 {11}3 {3}1\.00$/m);
    expect(result.out).toMatch(/^ {2}e2e .*0 {13}0 {11}1 {11}4 {6}-$/m);
    expect(result.out).not.toContain("test-ratio:");
  });

  it("prints the numbers as JSON with --json", () => {
    const root = writeTree();
    const result = run(["--json"], root);
    expect(result).toMatchObject({ status: 0, err: "" });
    expect(JSON.parse(result.out)).toEqual(initialReport);
    const checked = run(["--json", "--check"], root);
    expect(checked.status).toBe(1);
    expect(JSON.parse(checked.out)).toEqual(initialReport);
  });

  it("refuses an unknown option with exit 2", () => {
    const root = writeTree();
    const result = run(["--strict"], root);
    expect(result).toEqual({
      status: 2,
      out: "",
      err: "test-ratio: unknown option --strict\nusage: node tools/test-ratio.mjs [--check] [--json]\n",
    });
  });

  it("exits 1 with --check while a package is below one to one and 0 once every package reaches it", () => {
    const root = writeTree();
    const below = run(["--check"], root);
    expect(below.status).toBe(1);
    expect(below.out).toContain("packages/rex (src)\n");
    expect(below.err).toBe(
      "test-ratio: packages/rex has 0.69 lines of test code per line of source, below 1.00\n",
    );

    write(root, "packages/rex/src/core/beta.test.ts", numbered("bt", 6));
    const report = tools.measure(root);
    expect(report.packages[0]).toMatchObject({
      source: { files: 2, lines: 13 },
      test: { files: 4, lines: 15 },
      ratio: 15 / 13,
      ok: true,
    });
    expect(report.ok).toBe(true);
    const met = run(["--check"], root);
    expect(met).toMatchObject({ status: 0, err: "" });
    expect(met.out).toContain(
      "test-ratio: every package has at least 1.00 lines of test code per line of source\n",
    );

    write(root, "examples/demo/app/data/wallet.ts", numbered("d", 1));
    const demoBelow = run(["--check"], root);
    expect(demoBelow.status).toBe(1);
    expect(demoBelow.err).toBe(
      "test-ratio: examples/demo has 0.88 lines of test code per line of source, below 1.00\n",
    );
  });

  it("measures both packages of the repository from the command line", () => {
    const result = spawnSync(process.execPath, [script, "--json"], {
      cwd: repoRoot,
      encoding: "utf8",
    });
    expect({ status: result.status, stderr: result.stderr }).toEqual({ status: 0, stderr: "" });
    const report = JSON.parse(result.stdout) as RatioReport;
    expect(report.packages.map((pkg) => pkg.name)).toEqual(["packages/rex", "examples/demo"]);
    for (const pkg of report.packages) {
      expect(pkg.source.files).toBeGreaterThan(0);
      expect(pkg.test.files).toBeGreaterThan(0);
      expect(pkg.ratio).not.toBeNull();
      expect(pkg.directories.length).toBeGreaterThan(1);
    }
    expect(report.packages[0]?.directories.map((row) => row.directory)).toContain("src/core");
    expect(report.packages[1]?.directories.map((row) => row.directory)).toContain(
      "app/pages/portfolio",
    );
  });
});
