import type { PredicateJson } from "../core/policy.ts";
import type { Manifest, ManifestFlowStep } from "./types.ts";

export const AGENTS_MD_BANNER =
  "<!-- GENERATED by rex manifest from the app declarations. DO NOT EDIT: run rex manifest to regenerate. -->";

export const FOLDER_CONVENTION: readonly string[] = [
  "app/pages/<page>/page.ts: the page declaration (route, params, policy, actions, chrome, regions, overlays, states); imports entities, actions and policies, never React.",
  "app/pages/<page>/view.tsx: layout of regions only; imports regions and layout primitives, never hooks, data or parts.",
  "app/pages/<page>/states.tsx: one export per declared non-ready state; imports parts and DesignX, never hooks.",
  "app/pages/<page>/hooks/use<Name>.ts: page-private state and queries; imports app/data and actions, never components.",
  "app/pages/<page>/regions/<region>/region.tsx: binds hooks to parts; the only hook caller; never imports other regions or pages.",
  "app/pages/<page>/regions/<region>/parts/<Part>.tsx: pure components, props in, events out; import DesignX components and types only.",
  "app/pages/<page>/overlays/<Overlay>.tsx: sheets, dialogs and drawers with declared dismissal; import parts and DesignX, never data fetching.",
  "app/pages/<page>/test/: page tests.",
  "app/actions, app/entities, app/policies, app/flows: one declaration per file; app/components: DesignX copies; app/data: stores and queries.",
];

function cell(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

function list(values: readonly string[]): string {
  return values.length === 0 ? "-" : values.map(cell).join(", ");
}

function table(headers: readonly string[], rows: readonly (readonly string[])[]): string[] {
  if (rows.length === 0) return ["_None._"];
  return [
    `| ${headers.join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.join(" | ")} |`),
  ];
}

export function describePredicate(predicate: PredicateJson): string {
  switch (predicate.kind) {
    case "always":
      return "always";
    case "never":
      return "never";
    case "can":
      return predicate.policy
        ? `${predicate.policy}.can(${predicate.permission})`
        : `can(${predicate.permission})`;
    case "requires": {
      const clauses: string[] = [];
      if (predicate.unlocked) clauses.push("unlocked");
      if (predicate.account) clauses.push("account");
      if (predicate.custody) clauses.push(`custody ${predicate.custody.join("/")}`);
      if (predicate.permissions.length > 0) clauses.push(predicate.permissions.join(" + "));
      const prefix = predicate.policy ? `${predicate.policy}.requires` : "requires";
      return `${prefix}(${clauses.join(", ")})`;
    }
    case "allOf":
    case "anyOf":
      return `${predicate.kind}(${predicate.predicates.map(describePredicate).join(", ")})`;
  }
}

function describeStep(step: ManifestFlowStep): string {
  return step.kind === "action"
    ? `action ${step.action}`
    : `approval ${step.id} (${step.label}; ${describePredicate(step.approvers)})`;
}

export function renderAgentsMd(manifest: Manifest): string {
  const lines: string[] = [
    AGENTS_MD_BANNER,
    "",
    `# ${cell(manifest.app.name)}: agent guide`,
    "",
    "This app is built with Rex. Read `.rex/manifest.json` for the full machine-readable description; this file summarises it.",
    "",
    "## Pages",
    "",
    ...table(
      ["Page", "Route", "Title", "Policy", "Regions", "Overlays", "Actions", "States"],
      manifest.pages.map((entry) => [
        `\`${entry.id}\``,
        `\`${entry.route}\``,
        cell(entry.chrome.title),
        cell(describePredicate(entry.policy)),
        list(entry.regions),
        list(entry.overlays.map((overlay) => `${overlay.id} (${overlay.dismiss})`)),
        list(entry.actions),
        String(entry.states.length),
      ]),
    ),
    "",
    "## Actions",
    "",
    ...table(
      ["Action", "Label", "Effect", "Shortcut", "Policy", "Invalidates"],
      manifest.actions.map((entry) => [
        `\`${entry.id}\``,
        entry.label === null ? "-" : cell(entry.label),
        entry.effect,
        entry.shortcut === null ? "-" : `\`${entry.shortcut}\``,
        cell(describePredicate(entry.policy)),
        list(entry.invalidates),
      ]),
    ),
    "",
    'Invoke an action by its control (`data-rex="<page>/<action>"`), its shortcut, the URL `<route>?act=<action>&input=<json>` or the command palette (mod+k). Irreversible actions ask for confirmation on every route.',
    "",
    "## Entities",
    "",
    ...table(
      ["Entity", "Key", "Fields"],
      manifest.entities.map((entry) => [
        `\`${entry.id}\``,
        `\`${entry.key}\``,
        list(
          entry.fields.map(
            (field) => `${field.name}${field.required ? "" : "?"}: ${field.kind ?? "value"}`,
          ),
        ),
      ]),
    ),
    "",
    "## Policies",
    "",
    ...table(
      ["Policy", "Permissions"],
      manifest.policies.map((entry) => [`\`${entry.id}\``, list(entry.permissions)]),
    ),
    "",
    "## Flows",
    "",
    ...table(
      ["Flow", "Steps"],
      manifest.flows.map((entry) => [`\`${entry.id}\``, list(entry.steps.map(describeStep))]),
    ),
    "",
    "## Endpoints",
    "",
    ...table(
      ["Method", "Path", "Action", "Content type", "Policy"],
      manifest.actions
        .filter((entry) => entry.http !== null)
        .map((entry) => {
          const http = entry.http as NonNullable<typeof entry.http>;
          return [
            http.method,
            `\`${cell(http.path)}\``,
            `\`${entry.id}\``,
            http.contentType === null ? "application/json" : cell(http.contentType),
            cell(describePredicate(entry.policy)),
          ];
        }),
    ),
    "",
    "## Islands",
    "",
    ...table(
      ["Page", "Region", "Hydration"],
      manifest.pages.flatMap((entry) =>
        Object.entries(entry.islands).map(([region, mode]) => [
          `\`${entry.id}\``,
          `\`${region}\``,
          mode,
        ]),
      ),
    ),
    "",
    "## Redirects",
    "",
    ...table(
      ["Source", "Destination", "Status"],
      manifest.redirects.map((entry) => [
        `\`${cell(entry.source)}\``,
        `\`${cell(entry.destination)}\``,
        String(entry.status),
      ]),
    ),
    "",
    "## Locales",
    "",
    ...(manifest.i18n === null
      ? ["_None._"]
      : [
          `Routing: ${manifest.i18n.routing}. Switch with \`?locale=<locale>\`.`,
          "",
          ...table(
            ["Locale", "Default", "Direction"],
            manifest.i18n.locales.map((locale) => [
              `\`${cell(locale)}\``,
              locale === manifest.i18n?.default ? "yes" : "no",
              manifest.i18n?.direction[locale] ?? "ltr",
            ]),
          ),
        ]),
    "",
    "## Deploy",
    "",
    manifest.deploy === null
      ? "_None._"
      : `Host \`${manifest.deploy.host}\`, build target \`${manifest.deploy.target}\`.`,
    "",
    "## Folder convention",
    "",
    ...FOLDER_CONVENTION.map((line) => `- ${line}`),
    "",
    "Every page renders `data-rex-page`, every region `data-rex-region`, every overlay `data-rex-overlay`, and one `application/rex+json` sidecar script with id `rex-page`.",
    "",
  ];
  return lines.join("\n");
}
